services:
  db:
    platform: linux/x86_64
    image: mysql:9.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306